### ISSUE TITLE
Binding problem when attempting to access `this`

### ISSUE THREAD

**Issue by aconrad** [mikejsdev/mocha-param#5]
I'm trying to access properties set during the `beforeEach()` function but I can't access them. Here's a small script for illustration. The first test case doesn't use `itParam` and works as expected but the second one breaks when using `itParam`:

```javascript
// test.js
var assert = require('assert');
var itParam = require('mocha-param');

tests = [{input: 4, expected: -1}];

describe('Array', function() {

  beforeEach(function() {
    this.array = [1, 2, 3];
  })

  describe('#indexOf()', function() {

    it('should return -1 when the value is not present', function() {
      assert.equal(this.array.indexOf(4), -1);  // `this.array` === [1, 2, 3] as expected
    });

    itParam('should return ${value.expected} when the value is ${value.input}', tests, function(test) {
      assert.equal(this.array.indexOf(test.input), test.expected);  // `this.array` is undefined here
    });

  });
});
```

EDIT:
Here is the output:

```
./node_modules/mocha/bin/mocha test.js


  Array
    #indexOf()
      ✓ should return -1 when the value is not present
      1) should return -1 when the value is 4


  1 passing (9ms)
  1 failing

  1) Array #indexOf() should return -1 when the value is 4:
     TypeError: Cannot read property 'indexOf' of undefined
    at test.js:21:31
    at Context.<anonymous> (node_modules/mocha-param/lib/index.js:37:20)
```

**Comment by mikejsdev** [comment]
You have at least two options here. One is to not use the keyword 'this' to reference the array and to pull the array variable declaration out of the beforeEach scope, for example:

```
// test.js
var assert = require('assert');
var itParam = require('mocha-param');

tests = [{ input: 4, expected: -1 }];
let array;

describe('Array', function () {

    beforeEach(function () {
        array = [1, 2, 3];
    })

    describe('#indexOf()', function () {

        it('should return -1 when the value is not present', function () {
            assert.equal(array.indexOf(4), -1);  // `this.array` === [1, 2, 3] as expected
        });

        itParam('should return ${value.expected} when the value is ${value.input}', tests, function (test) {
            assert.equal(array.indexOf(test.input), test.expected);  // `this.array` is undefined here
        });

    });
});
```



The other is to use arrow functions '()=>' instead of  the 'function' keyword as arrow functions have a lexical 'this'. The following will work too:

```
// test.js
var assert = require('assert');
var itParam = require('mocha-param');

tests = [{ input: 4, expected: -1 }];

describe('Array', () => {

    beforeEach(() => {
        this.array = [1, 2, 3];
    })

    describe('#indexOf()', () => {

        it('should return -1 when the value is not present', () => {
            assert.equal(this.array.indexOf(4), -1);  // `this.array` === [1, 2, 3] as expected
        });

        itParam('should return ${value.expected} when the value is ${value.input}', tests, (test) => {
            assert.equal(this.array.indexOf(test.input), test.expected);  // `this.array` is undefined here
        });

    });
});
```

I hope this helps.
Mike

**Comment by aconrad** [comment]
Thanks for your response @mikejsdev. I understand the workaround, but it would be nicer if `itParam` had the same interface and worked similarily as `it`.

On that note, I noticed that I can't do `itParam.only(...)`, but that might be for a separate issue (we might just need to return the underlying `it` object).

**Comment by mikejsdev** [comment]
I'm closing this as it's been open for a while and there is a work around.

**Comment by HoldYourWaffle** [comment]
The arrow-function workaround didn't work for me, but after a couple of frustrating hours I managed to find the solution (#13)

**Comment by Bartel-C8** [comment]
UP for the PR. As I need to increase the timeout value of the mocha tests. For which I need to use `this.timeout(100000)`...
